//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMTrayIcon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMTrayIcon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAABAAYAAAAAAAEAIABkdAAAZgAAAICAAAABACAAKQgBAMp0AABAQAAAAQAgAClCAADzfAEAMDAAAAEAIACpJQAAHL8BACAgAAABACAAqRAAAMXkAQAQEAAAAQAgAGkEAABu9QEAiVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAB0K0lEQVR42uxdB4DURBd+WXpHEAsKdjgVKypWylmwgGJHkaaCoNgbclSlKSpSFQERsNEUBQuKwK9gbyggIHZBFBtSpNwl/0wy5U1Jdu9u28E92Es2ySYzk3nfqzPjQCmVaMrJva8WQKw+gLc/gFOXHNqHfPZkH3IOapJPNfapRD4Vyacs22LaRj75bPsf+Wxin3/I5y/y+YN9fiWfdeSz1gP3p1ULhvyV6TYopaKTk+kClFJ8atCiZ2XHiR1OXtYR5JWRDxxKPoeRz0HkUz3DxfuXfL4jn2/JZxX5fEM+yz0oWLZqwdD/Mly2UopDpQCQZZSTm1eV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconMain {
            get {
                return ResourceManager.GetString("IconMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconOff {
            get {
                return ResourceManager.GetString("IconOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAQAQAAAAAAAAAAAAAAAAAAAAAAAD8+fMA/PnzAPr38gD49vEA+PbxAPj28QD49vEA+PbxAPj28QD49vEA+PbxAPj28QD49vEA+vfyAPz58wD8+fMA/PnzAPz58wDh5OIA2t7fANnd3gDZ3d4A2d3eANnd3gDZ3d4A2d3eANnd3gDZ3d4A2t7fAOHl4wD8+fMA/PnzAJa70gAEYKH/CV2h/wxZov8NWaL/DVmi/w1Zov8OWaL/Dlmi/w5Zov8OWaL/Dlmi/w5XoP8NVZf/gaC2APv48gABYaH/XPX//w/s//8T4///GN3//xrY//8c1f//HNT//xzU//8c1P//HNT//xzU//8b1P//FdX//wxVm//V2twAAGCh/8X3//9a8///W+v//1zf//8h1///ItT//yLT//8i0///ItP//yLT//8i0///IdP//xvU//8NWKH/09fZAABg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconOn {
            get {
                return ResourceManager.GetString("IconOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAABAAYAAAAAAAEAIAA4ZgAAZgAAAICAAAABACAAKAgBAJ5mAABAQAAAAQAgAChCAADGbgEAMDAAAAEAIACoJQAA7rABACAgAAABACAAqBAAAJbWAQAQEAAAAQAgAGgEAAA+5wEAiVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAABl/0lEQVR42u1dCaAN1Rv/5tr3PfsS4REqKZTtvYiKUP0lspW1pLRInrVsJdmVkC2FKKFFZanIkkjZnkohUrIvWd678z9nZs6cZc7c7d07c98zP+bN3LlzZ86cme93vu2co4CHDI2EpJcKA/jKAahlAJRSaFcJtBQ1FvQdFERLPmPJhZacaMlqrFlcQkuqsf4PLeeM5TRaTqLlX2P5Cy1H0XJEBf+hlLVjTrpdBx4ih+J2ATwER5XEgbkVxVcNPazq6JGhBW5AS2W0XI+W/C4X7yxaDqDlN7SkoOUXtOxWIW1Xytqx/7lcNg9B4BFAnCEhKTkvas1v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IconRed {
            get {
                return ResourceManager.GetString("IconRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UklGRmKxAgBXQVZFZm10IBAAAAABAAIARKwAABCxAgAEABAATElTVBoAAABJTkZPSVNGVA4AAABMYXZmNTguMTcuMTAxAGRhdGEcsQIAqP++/zsASgDQAtYCYAdcB/sM6wx2ElgSHxfyFvQatRowHt8d7SCJIBkjoSKxJCMk0iUvJYYmziWjJtUl8CUOJXYkgSONIoUhjCB0H4EeWh09HAsbqBltGPYWtRWCFD8TgxJAEeUQpg9xDzkOBw7aDLwMnAvAC7IKNgs7ChMLLwonC1sKPAuLCj8LqQpBC8gKWQv+CnMLNgtUCzULxwrFCssJ5QmCCLYI+QZHBxIFdwWoAiIDwf9OAIz8Kv0o+dX5g/U89oPxRvI97Qju+ujM6ffkzuU34RHipt2B3ljaNduW13PYldVy1kbUI9V001DUCdPm0y7TCtQQ1OzUqtWI1tTXs9h02lXblt143j7hIuI/5STmT+k16kntMO448R/yJ/UN9u740flC/CD9/P7V/zYB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SoundMessage {
            get {
                return ResourceManager.GetString("SoundMessage", resourceCulture);
            }
        }
    }
}
